# Generated by Django 3.0.7 on 2020-06-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20200608_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='specialty',
            field=models.BooleanField(default=False),
        ),
    ]
