# Generated by Django 3.0.7 on 2020-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meals_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='specialty',
        ),
        migrations.AddField(
            model_name='meals',
            name='spcialty',
            field=models.BooleanField(default=False),
        ),
    ]
